#version 460 core
#extension GL_EXT_shader_explicit_arithmetic_types_float32 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int32 : require
#extension GL_KHR_shader_subgroup_arithmetic : require

layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform PushConstants {
    layout(offset = 0) uint32_t input_len;
} push_const;

layout(binding = 0) restrict readonly buffer InputBuffer {
    f32vec4[] input_buf;
};

layout(binding = 1) restrict writeonly buffer OutputBuffer {
    f32vec4[] output_buf;
};

void main() {
    if (gl_GlobalInvocationID.x >= push_const.input_len) {
        return;
    }

    f32vec4 avg_position = subgroupAdd(input_buf[gl_GlobalInvocationID.x]);

    if (subgroupElect()) {
        output_buf[gl_WorkGroupID.x] = avg_position;
    }
}
