#version 460 core
#extension GL_EXT_shader_explicit_arithmetic_types_int32 : require
#extension GL_KHR_shader_subgroup_arithmetic : require

layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0) restrict readonly buffer InputBuffer {
    uint32_t input_buf[];
};

layout(binding = 1) restrict writeonly buffer WorkgroupBuffer {
    uint32_t workgroup_buf[];
};

void main() {
    uint32_t sum = subgroupAdd(input_buf[gl_GlobalInvocationID.x]);

    if (subgroupElect()) {
        workgroup_buf[gl_WorkGroupID.x] = sum;
    }
}
